### PR TITLE
Fix: Propose UI stuck partway through process

### LINKED ISSUE #244: Propose: UI stuck partway through process
**Describe the bug**
I just tried to use the Propose that comes up when you click the three dots in the upper right of a post and I think it may be broken, at least the UI isn't indicating the process was completed successfully, etc.  

**To Reproduce**

1. I made a Request post: https://near.social/mob.near/widget/MainPage.N.Post.Page?accountId=dawnkelly.near&blockHeight=116614755
2. Clicked the three dots in upper right corner of the post and selected Propose
3. The proposal modal popped up, I selected Text for my Proposal Type and the embed for my post was auto-populated (see screenshot below)
4. I clicked Next, the modal popped up showing the SocialDB data object to be saved and buttons to Confirm or Cancel, I selected Confirm and signed the wallet transaction
5. When the wallet transaction is finished, I'm taken back to the Propose modal with no indication of whether or not things succeeded. My only two options are to close the Propose modal or hit Next which repeats the saving of the same data. 

**Expected behavior**
Everything is good through step 4 where you save data and sign the transaction in the wallet. Works great. 

I would expect the wallet transaction to finish and then get some indication from the UI that the proposal was submitted successfully. This could look like a pop-up/toast with a message or a redirect to the Proposals feed where I would see my Proposal at/near the top of the list as one of the newest submissions. 

**Screenshots**
Propose

**Desktop (please complete the following information):**

- OS: iOS
- Browser Chrome
- Version 

**Additional context**
The proposals were submitted successfully on-chain. 
Transaction hashes:
https://nearblocks.io/txns/9LkhvMoWcTwnBvDD3smCaGyDsqmhFDNjLM9BRfSAXjrz
https://nearblocks.io/txns/B2EYdMArSu4JUr6LXPbRcXYmLqkxyhXSpFRZFKP5r4EC

I was not able to see them on the Proposal Feed earlier. I can't confirm if that is still the case as the Proposal widget seems to be down or being worked on right now.

### PR DESCRIPTION
**Pull request by Eren-Yeaager**
Resolves #244 

https://drive.google.com/file/d/1f0C3GOwhMxGZrof3OOYEDFmI7yqJGpe7/view?usp=drive_link

New design Implementation: 
https://drive.google.com/file/d/1VEEuDqmXkeb50bCO5IfT0LVochw7Njkl/view?usp=sharing

New changes introduced :
https://drive.google.com/file/d/1SR39jcrweG71jNfsXrKgKMG0tK13BeT8/view?usp=drive_link

### CODE REVIEW

File: apps/builddao/widget/components/modals/propose/AddMember.jsx [hunk 1]
```diff
@@ -1,12 +1,20 @@
...
+  "${config_account}/widget/components.modals.InfoAlert",
+) || {
+  InfoPopup: () => <></>,
+};
 const DaoSDK =
   VM.require("sdks.near/widget/SDKs.Sputnik.DaoSDK") || (() => <></>);
 
 const [accountId, setAccountId] = useState("");
 const [role, setRole] = useState("");
+const [infoPopup, setInfoPopup] = useState(false);
```
Comment (Megha-Dev-19) [inline apps/builddao/widget/components/modals/propose/AddMember.jsx:14]:
```suggestion
const [isInfoModalActive, setInfoModalActive] = useState(false);
```

File: apps/builddao/widget/components/modals/propose/AddMember.jsx [hunk 2]
```diff
@@ -1,12 +1,20 @@
...
+const [copied, setCopied] = useState(false);
+const url =
+  "https://www.nearbuilders.org/buildhub.near/widget/app?page=feed&tab=proposals";
```
Comment (Megha-Dev-19) [inline apps/builddao/widget/components/modals/propose/AddMember.jsx:17]: let's update this
btw, why do we have this in two places?

File: apps/builddao/widget/components/modals/propose/RemoveMember.jsx [hunk 3]
```diff
@@ -167,6 +176,38 @@ const TextareaWrapper = styled.div`
...
+    timeoutId = setTimeout(() => {
+      setCopied(false);
+    }, 2000);
+  }
+
+  return () => clearTimeout(timeoutId);
+}, [copied]);
+
+const handleCopy = () => {
+  clipboard
```
Comment (Megha-Dev-19) [inline apps/builddao/widget/components/modals/propose/RemoveMember.jsx:201]: ahh so copy doesn't work from info widget?

**Review by Megha-Dev-19 — CHANGES_REQUESTED** [review]
Good job with your first ticket
@Eren-Yeaager left few comments

File: apps/builddao/widget/components/modals/propose/RemoveMember.jsx (hunk 3 above)
Comment (Eren-Yeaager) [reply apps/builddao/widget/components/modals/propose/RemoveMember.jsx:201]: no actually I got to know that we cant use state and then import it through VM

File: apps/builddao/widget/components/modals/propose/AddMember.jsx (hunk 2 above)
Comment (Eren-Yeaager) [reply apps/builddao/widget/components/modals/propose/AddMember.jsx:17]: Yeah I will update this :)

File: apps/builddao/widget/components/modals/InfoAlert.jsx [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+              marginLeft: "-10px",
+              marginBottom: "20px",
+            }}
+          >
+            <h5>
+              After approval, the proposal will appear in the Proposals feed.
+              Please copy the link of the feed beforehand.
+            </h5>
+          </p>
+          <div style={{ textAlign: "center", marginTop: "10px" }}>
```
[the remark this answers is not in the document]
Comment (Eren-Yeaager) [reply apps/builddao/widget/components/modals/InfoAlert.jsx:26]: Sure will use classes.

File: apps/builddao/widget/components/modals/propose/Transfer.jsx [hunk 5]
```diff
@@ -1,13 +1,22 @@
...
 
 const [recipient, setRecipient] = useState("");
 const [token, setToken] = useState("");
 const [amount, setAmount] = useState(0);
 const [description, setDescription] = useState("");
 const [validatedAddresss, setValidatedAddress] = useState(true);
+const [isInfoModalActive, setInfoModalActive] = useState(false);
+const [copied, setCopied] = useState(false);
+const url =
+  "https://www.nearbuilders.org/buildhub.near/widget/app?page=feed&tab=proposals";
```
Comment (elliotBraem) [inline apps/builddao/widget/components/modals/propose/Transfer.jsx:19]: I see this url in quite a few cases; in each of them we want it to be the correct url according to environment. For this, we use [bos-workspace aliases](https://github.com/NEARBuilders/bos-workspace?tab=readme-ov-file#aliases).

I think this should be:
`${alias_gateway_url}/${config_account}/widget/app?page=feed&tab=proposals`

File: apps/builddao/widget/components/modals/propose/RemoveMember.jsx (hunk 3 above)
Comment (Megha-Dev-19) [reply apps/builddao/widget/components/modals/propose/RemoveMember.jsx:201]: why don't we have this inside the InfoPopup component?
because we need it for all modals right?

File: apps/builddao/widget/components/modals/VisibilityModal.jsx [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+  overflow-y: auto;
+  z-index: 1000;
+  width: 100vw;
+  height: 100vh;
+  background: var(--modal-overlay-color, rgba(35, 36, 43, 0.7));
+`;
+
+function VisibilityModal({
+  children,
+  title,
```
Comment (Megha-Dev-19) [inline apps/builddao/widget/components/modals/VisibilityModal.jsx:18]: why do we have this?
we already have a `Modal` component right?

File: apps/builddao/widget/components/modals/propose/ProposalVisibilityInfoModal.jsx [hunk 7]
```diff
@@ -1,7 +1,91 @@
...
 };
+const { VisibilityModal } = VM.require(
+  "${config_account}/widget/components.modals.VisibilityModal",
+) || {
+  VisibilityModal: () => <></>,
+};
+
+const ModalContainer = styled.div`
+  width: 480px;
+  height: 314px;
```
Comment (Megha-Dev-19) [inline apps/builddao/widget/components/modals/propose/ProposalVisibilityInfoModal.jsx:12]: why can't we move the copytoClipboard code in this widget itself?

Comment (Eren-Yeaager) [reply apps/builddao/widget/components/modals/propose/ProposalVisibilityInfoModal.jsx:10]: Sure moved it to the widget

File: apps/builddao/widget/components/modals/VisibilityModal.jsx (hunk 6 above)
Comment (Eren-Yeaager) [reply apps/builddao/widget/components/modals/VisibilityModal.jsx]: Yes. Utilized the Modal component now.

File: apps/builddao/widget/components/modals/propose/Transfer.jsx (hunk 5 above)
Comment (Eren-Yeaager) [reply apps/builddao/widget/components/modals/propose/Transfer.jsx]: Sure .Implemented this.

**Comment by elliotBraem** [comment]
Can we resolve conflicts please?

File: apps/old/widget/components/modals/propose/AddMember.jsx [hunk 8]
```diff
@@ -1,12 +1,19 @@
...
+) || {
+  ProposalVisibilityInfoModal: () => <></>,
+};
 const DaoSDK =
   VM.require("sdks.near/widget/SDKs.Sputnik.DaoSDK") || (() => <></>);
 
 const [accountId, setAccountId] = useState("");
 const [role, setRole] = useState("");
+const [isInfoModalActive, setInfoModalActive] = useState(false);
+const [copied, setCopied] = useState(false);
```
Comment (Megha-Dev-19) [inline apps/old/widget/components/modals/propose/AddMember.jsx:15]: Why do we need this ?

File: apps/old/widget/components/modals/propose/ProposalVisibilityInfoModal.jsx [hunk 9]
```diff
@@ -0,0 +1,138 @@
...
+  sdkCall,
+}) => {
+  const handleCopy = () => {
+    clipboard
+      .writeText(url)
+      .then(() => {
+        setCopied(true);
+        sdkCall(); // Call the function to create proposal
+        setTimeout(() => {
+          setCopied(false);
```
Comment (Megha-Dev-19) [inline apps/old/widget/components/modals/propose/ProposalVisibilityInfoModal.jsx:97]: Why do we need this timeout? Can’t we call it directly ?

**Review by Megha-Dev-19 — COMMENTED** [review]
Left few comments, @Eren-Yeaager can you please resolve the above comments which are done.

File: apps/builddao/widget/components/modals/propose/AddMember.jsx (hunk 1 above)
Comment (Eren-Yeaager) [reply apps/builddao/widget/components/modals/propose/AddMember.jsx]: Done !

File: apps/old/widget/components/modals/propose/AddMember.jsx (hunk 8 above)
Comment (Eren-Yeaager) [reply apps/old/widget/components/modals/propose/AddMember.jsx]: Removed it .

File: apps/old/widget/components/modals/propose/ProposalVisibilityInfoModal.jsx (hunk 9 above)
Comment (Eren-Yeaager) [reply apps/old/widget/components/modals/propose/ProposalVisibilityInfoModal.jsx]: Removed the timeout.

**Review by Megha-Dev-19 — APPROVED** [review]
LGTM, can you please run format command once and them merge it

**Comment by Eren-Yeaager** [comment]
> LGTM, can you please run format command once and them merge it

Sure
